// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADemu0Hl83nVoTlhzOs3bXF3SJhTyS5SI',
    appId: '1:137812451181:web:f725bb637656791563c464',
    messagingSenderId: '137812451181',
    projectId: 'flutter--storage-33b33',
    authDomain: 'flutter--storage-33b33.firebaseapp.com',
    storageBucket: 'flutter--storage-33b33.appspot.com',
    measurementId: 'G-XJT5Z0XW0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysf4OdFPfUHpAup474xRrPPQokOZfwSE',
    appId: '1:137812451181:android:de8c54430a6866ca63c464',
    messagingSenderId: '137812451181',
    projectId: 'flutter--storage-33b33',
    storageBucket: 'flutter--storage-33b33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApuKC0YqrczxwOaD_AO0DVUfjApUy-aAI',
    appId: '1:137812451181:ios:c3a8efe200842fe463c464',
    messagingSenderId: '137812451181',
    projectId: 'flutter--storage-33b33',
    storageBucket: 'flutter--storage-33b33.appspot.com',
    iosBundleId: 'com.example.flutterSecureStoragePlugin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApuKC0YqrczxwOaD_AO0DVUfjApUy-aAI',
    appId: '1:137812451181:ios:71e69a91f6b7c4cb63c464',
    messagingSenderId: '137812451181',
    projectId: 'flutter--storage-33b33',
    storageBucket: 'flutter--storage-33b33.appspot.com',
    iosBundleId: 'com.example.flutterSecureStoragePlugin.RunnerTests',
  );
}
